sudo: required
services:
  - docker

before_install:
  - docker build -t jayden003/react-test -f ./client/Dockerfile.dev ./client
  - docker build -t jayden003/react-test-nginx -f ./nginx/Dockerfile.dev ./nginx

script:
  - docker run jayden003/react-test npm test -- --coverage

after_success:
  - docker build -t jayden003/multi-client ./client
  - docker build -t jayden003/multi-nginx ./nginx
  - docker build -t jayden003/multi-server ./server
  - docker build -t jayden003/multi-worker ./worker
  #log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push jayden003/multi-client
  - docker push jayden003/multi-nginx
  - docker push jayden003/multi-server
  - docker push jayden003/multi-worker
